### ISSUE TITLE
Unable to install `optimum-nvidia` on Ubuntu

### ISSUE THREAD

**Issue by QuantumStaticFR** [huggingface/optimum-nvidia#144]
## Platform
Ubuntu: 24.04 LTS
Python: 3.8/3.10/3.12

## Steps

1. Created a fresh python virtual environment `python3.x -m venv myvenv` and activated it
2. First run `pip install optimum`
3. Then try running `pip install optimum-nvidia`

### Python 3.8

```bash
ERROR: Ignored the following versions that require a different python version: 0.1.0b5 Requires-Python >=3.10; 0.1.0b6 Requires-Python >=3.10; 0.1.0b7 Requires-Python >=3.10
ERROR: Could not find a version that satisfies the requirement optimum-nvidia (from versions: none)
ERROR: No matching distribution found for optimum-nvidia
```

### Python 3.10

```bash
Collecting nvidia-ammo~=0.7.0
  Downloading nvidia-ammo-0.7.4.tar.gz (6.9 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-cbuy0b6u/nvidia-ammo_ab45a6d46c164fb680b975db6a9a2ff3/setup.py", line 90, in <module>
          raise RuntimeError("Bad params")
      RuntimeError: Bad params
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
```

### Python 3.12
```bash
Collecting tensorrt==9.3.0.post12.dev1 (from tensorrt-llm==0.9.0->optimum-nvidia)
  Downloading tensorrt-9.3.0.post12.dev1.tar.gz (6.9 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "/home/path/to/optimum/optimumvenv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/path/to/optimum/optimumvenv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/path/to/optimum/optimumvenv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-vvzluoxx/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 327, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-vvzluoxx/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 297, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-vvzluoxx/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 497, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-vvzluoxx/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 313, in run_setup
          exec(code, locals())
        File "<string>", line 90, in <module>
      RuntimeError: Bad params
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.
```

**Comment by mfuntowicz** [comment]
Thanks @QuantumStaticFR and sorry you are having issue installing `optimum-nvidia`.

I would recommand forwarding this error to the TensorRT-LLM repository because the error you're facing is due to the transitive dependency on MPI from TensorRT-LLM.

Also on a general note: You should stick to Python3.10 this is the supported Python version for TensorRT-LLM

@laikhtewari for viz on Nvidia side

**Comment by TanvirKasir786** [comment]
conda install mpi4py solved the issue for me. Make sure you are using python 3.10. If your environment is already using python 3.10 then use the following:
apt-get update && apt-get -y install openmpi-bin libopenmpi-dev
conda install mpi4py or python -m pip install mpi4py
python -m pip install --pre --extra-index-url https://pypi.nvidia.com optimum-nvidia
